### ISSUE TITLE
[svelte + graphql + codegen] - seed

### ISSUE THREAD

**Issue by jycouet** [ticruz38/graphql-codegen-svelte-apollo#1]
Great to see a codegen plugin with svelte 👍 
By chance, do you have a seed project with the combination of [svelte + graphql + codegen]?

Let me know

**Comment by ticruz38** [comment]
I currently use it on private repos,
But you're right, I will make an example folder with a use case

**Comment by ticruz38** [comment]
I have put together an example in the example folder, you can start from there, it uses the public SpaceX Graphql API, you will find an example with both a stateless and stateful query.
I recommend using Webpack instead of Rollup for faster development builds.
There is a script named type in the package.json that needs to be run every time you add a query in a .gql file.
You should use the VScode extension GraphQL by the GraphQL Foundation, for autocomplete in your .gql files.
